services:
  ive:
    depends_on:
      - redis
      - minio
    image: docker.ait-younes.fr/ive/ive
    env_file:
      - .env
  worker:
    depends_on:
      - redis
      - minio
    image: docker.ait-younes.fr/ive/worker
    environment:
      - IVE_S3_URL=http://minio:9000
      - IVE_REDIS_URL=redis://redis/
  redis:
    image: "redis"
    command: redis-server --protected-mode no --bind 0.0.0.0
    ports:
      - '6379:6379'
  minio:
    entrypoint: sh
    command: -c 'mkdir -p /data/ive && minio server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
